### PR TITLE
Re-added V1 torrent file and removed old source zip

### PR DESCRIPTION
**Pull request by Mipsters**
Noticed the v1 torrent button does not work anymore so I fixed it
I prefer torrent to most of the other options because it relays less on other services
I would also suggest to make the patch available via torrent too, or the whole v2
although both options may become messy to maintain...

### CODE REVIEW

**Comment by Mipsters** [comment]
On that note, the content of the .gitignore file is probably not needed too?

**Comment by Mipsters** [comment]
@Bambosh hey, I don't want to nag you but I do think that keeping the torrent file alive is important
homestuck suffered a lot of loses due to lack of backup over the years, and torrent is really the ultimate way to battle that
that is why I think its critical to keep the torrent up, or make a new one of the V2

**Comment by foxsouns** [comment]
+1

**Comment by Mipsters** [comment]
thank you :)

**Pull request merged**
